Repository gitbucket/gitbucket, pull requests merged in 2018-05, with the labels that each got.

#1996 Fix JSON diff issue.
  src/main/webapp/assets/common/js/gitbucket.js
Labels: bug

#2006 Download a correct patch file on PR screen
  src/main/twirl/gitbucket/core/pulls/files.scala.html
Labels: bug

#1989 Show mail address in profile page
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/twirl/gitbucket/core/account/activity.scala.html
  src/main/twirl/gitbucket/core/account/main.scala.html
  src/main/twirl/gitbucket/core/account/members.scala.html
  src/main/twirl/gitbucket/core/account/repositories.scala.html
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: feature

#1986 set ace editor mode by ext-modelist.js
  src/main/scala/gitbucket/core/view/helpers.scala
  src/main/twirl/gitbucket/core/repo/editor.scala.html
Labels: improvement

#2011 Use SecureRandom to generate access tokens.
  src/main/scala/gitbucket/core/service/AccessTokenService.scala
Labels: improvement

#2019 Disabled a checkbox of tasklist on preview
  src/main/twirl/gitbucket/core/helper/preview.scala.html
Labels: improvement

#2013 Change to avatar image link from avatar image
  src/main/twirl/gitbucket/core/account/members.scala.html
  src/main/twirl/gitbucket/core/admin/userlist.scala.html
  src/main/twirl/gitbucket/core/helper/activities.scala.html
  src/main/twirl/gitbucket/core/helper/commitcomment.scala.html
  src/main/twirl/gitbucket/core/issues/commentlist.scala.html
  src/main/twirl/gitbucket/core/issues/issueinfo.scala.html
  src/main/twirl/gitbucket/core/pulls/compare.scala.html
  src/main/twirl/gitbucket/core/releases/list.scala.html
  src/main/twirl/gitbucket/core/releases/release.scala.html
  src/main/twirl/gitbucket/core/repo/blob.scala.html
  src/main/twirl/gitbucket/core/repo/commit.scala.html
  src/main/twirl/gitbucket/core/repo/files.scala.html
  src/main/twirl/gitbucket/core/repo/forked.scala.html
  src/main/twirl/gitbucket/core/wiki/history.scala.html
Labels: improvement

#2016 Create comment on changing issue title
  doc/comment_action.md
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/twirl/gitbucket/core/issues/commentlist.scala.html
Labels: improvement

#2014 improve archive download
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/main/twirl/gitbucket/core/repo/files.scala.html
Labels: improvement

#2017 use PBKDF2 for password
  src/main/resources/update/gitbucket-core_4.25.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/service/AccountService.scala
  src/main/scala/gitbucket/core/util/StringUtil.scala
Labels: improvement

#2026 show "edited" in edited comment
  src/main/twirl/gitbucket/core/helper/commitcomment.scala.html
  src/main/twirl/gitbucket/core/issues/commentlist.scala.html
Labels: improvement

#2028 expose user pubkey via /{user}.keys
  src/main/scala/gitbucket/core/controller/AccountController.scala
Labels: feature

#2027 Fix for repository downloading improvement
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
Labels: improvement

#2015 Counting conversations on pull request screen
  src/main/twirl/gitbucket/core/pulls/menu.scala.html
Labels: bug

#2032 fix extra email bug in account registration
  src/main/scala/gitbucket/core/controller/AccountController.scala
Labels: bug

#2034 Migration to delete empty extra mail addresses
  src/main/resources/update/gitbucket-core_4.25.xml
Labels: bug
