Repository gitbucket/gitbucket, pull requests merged in 2018-11, with the labels that each got.

#2178 Allow to redirect to Release page from activity
  src/main/scala/gitbucket/core/service/ActivityService.scala
  src/main/scala/gitbucket/core/view/helpers.scala
Labels: feature

#2177 Remove repeat plugin name
  src/main/twirl/gitbucket/core/admin/plugins.scala.html
Labels: improvement

#2189 Fix link rendering in Markdown
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/plugin/Renderer.scala
  src/main/scala/gitbucket/core/view/Markdown.scala
  src/main/scala/gitbucket/core/view/helpers.scala
  src/main/twirl/gitbucket/core/helper/commitcomment.scala.html
  src/main/twirl/gitbucket/core/issues/commentlist.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/list.scala.html
  src/main/twirl/gitbucket/core/pulls/mergeguide.scala.html
  src/main/twirl/gitbucket/core/releases/list.scala.html
  src/main/twirl/gitbucket/core/releases/release.scala.html
  src/main/twirl/gitbucket/core/wiki/page.scala.html
Labels: bug

#2192 Set the commit datetime to archive entries
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
Labels: bug

#2196 Fix authorization for group web hook configuration page
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/util/Authenticator.scala
Labels: bug

#2199 Add new extension point: anonymousAccessiblePaths
  src/main/scala/gitbucket/core/controller/PreProcessController.scala
  src/main/scala/gitbucket/core/plugin/Plugin.scala
  src/main/scala/gitbucket/core/plugin/PluginRegistry.scala
Labels: feature
