Repository gitbucket/gitbucket, pull requests merged in 2018-04, with the labels that each got.

#1923 Add scalafmt
  .scalafmt.conf
  build.sbt
  project/plugins.sbt
Labels: task

#1940 Fix a bug that fails to get the list of files of the repository root
  src/main/scala/gitbucket/core/controller/ApiController.scala
Labels: bug

#1954 Keep wrap mode of Ace editor using localStorage
  src/main/twirl/gitbucket/core/repo/editor.scala.html
Labels: improvement

#1957 fix #1956
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
Labels: bug

#1942 Add X-Forwarded-Proto support for baseurl parsing
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
Labels: improvement

#1955 Improve webhook payload compatibility for discord.
  src/main/scala/gitbucket/core/api/ApiIssue.scala
  src/main/scala/gitbucket/core/api/ApiPullRequest.scala
  src/main/scala/gitbucket/core/api/ApiRepository.scala
  src/main/scala/gitbucket/core/api/ApiUser.scala
  src/test/scala/gitbucket/core/api/JsonFormatSpec.scala
Labels: improvement

#1959 Apply ApiAuthenticationFilter to /api/* to cover APIs other than GitHub API
  src/main/scala/ScalatraBootstrap.scala
  src/main/scala/gitbucket/core/controller/ControllerBase.scala
Labels: improvement

#1953 Disable removed user's repositories
  src/main/scala/gitbucket/core/service/RepositoryService.scala
Labels: bug

#1980 show tags on commits page
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/main/twirl/gitbucket/core/repo/commits.scala.html
Labels: improvement

#1982 don't separate user:branch in PR message
  src/main/twirl/gitbucket/core/pulls/menu.scala.html
Labels: bug

#1983 close and mark as merged PR by pushed commits
  src/main/scala/gitbucket/core/service/PullRequestService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
Labels: feature

#1984 call issue closed webhook when pushed commit contains keywords
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
Labels: bug

#1988 Fix editor preview bug
  src/main/twirl/gitbucket/core/repo/editor.scala.html
Labels: bug
