Repository gitbucket/gitbucket, pull requests merged in 2018-07, with the labels that each got.

#1966 Support EditorConfig for online browser/editor.
  build.sbt
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/util/EditorConfigUtil.scala
  src/main/twirl/gitbucket/core/repo/blob.scala.html
  src/main/twirl/gitbucket/core/repo/editor.scala.html
  src/test/scala/gitbucket/core/util/EditorConfigUtilSpec.scala
Labels: improvement

#2106 Catch network exceptions (UnknownHostException etc.)
  src/main/scala/gitbucket/core/plugin/PluginRepository.scala
Labels: improvement

#2110 Separate issues and pull requests search
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/service/RepositorySearchService.scala
  src/main/twirl/gitbucket/core/issues/list.scala.html
  src/main/twirl/gitbucket/core/search/issues.scala.html
  src/main/twirl/gitbucket/core/search/menu.scala.html
  src/main/twirl/gitbucket/core/search/wiki.scala.html
Labels: improvement

#2115 BugFix for the file remove page
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/twirl/gitbucket/core/helper/diff.scala.html
  src/main/twirl/gitbucket/core/repo/delete.scala.html
  src/main/webapp/assets/common/js/gitbucket.js
Labels: bug

#1967 add tag on commit.
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/main/twirl/gitbucket/core/repo/commit.scala.html
Labels: feature

#2105 Proxy support for plugin installation
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/plugin/PluginRegistry.scala
  src/main/scala/gitbucket/core/plugin/PluginRepository.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/scala/gitbucket/core/util/HttpClientUtil.scala
  src/main/twirl/gitbucket/core/admin/plugins.scala.html
  src/main/twirl/gitbucket/core/admin/settings.scala.html
  src/main/twirl/gitbucket/core/admin/settings_plugins.scala.html
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: improvement
