Repository gitbucket/gitbucket, pull requests merged in 2018-06, with the labels that each got.

#2043 Move buttons into commentform area
  src/main/twirl/gitbucket/core/repo/commentform.scala.html
Labels: improvement

#2044 Release the disable status on line comment adding button when validation error occurred
  src/main/twirl/gitbucket/core/repo/commentform.scala.html
Labels: bug

#2018 Add notification hooks
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/plugin/IssueHook.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
Labels: improvement

#2037 Focus to textarea at add and edit a comment
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/twirl/gitbucket/core/helper/preview.scala.html
  src/main/twirl/gitbucket/core/issues/editcomment.scala.html
  src/main/twirl/gitbucket/core/issues/editissue.scala.html
  src/main/twirl/gitbucket/core/repo/commentform.scala.html
  src/main/twirl/gitbucket/core/repo/editcomment.scala.html
Labels: improvement

#2042 Keep showing a fold comment when tasklist is not complete
  src/main/twirl/gitbucket/core/helper/commitcomments.scala.html
Labels: improvement

#2066 Render HTML as text/plain
  src/main/scala/gitbucket/core/controller/ControllerBase.scala
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/controller/ReleasesController.scala
  src/main/scala/gitbucket/core/servlet/PluginAssetsServlet.scala
  src/main/scala/gitbucket/core/util/FileUtil.scala
Labels: improvement

#2047 Added mime-type mapping for SVG files
  src/main/webapp/WEB-INF/web.xml
Labels: improvement

#2067 Adjust condition to display pull request creation suggestion for branches
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
Labels: improvement

#2075 Fork account selector dialog to be list style
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/twirl/gitbucket/core/helper/forkrepository.scala.html
  src/main/twirl/gitbucket/core/repo/forked.scala.html
  src/main/webapp/assets/vendors/facebox/facebox.css
Labels: improvement

#2074 Add "Repositories" tab to the dashboard
  src/main/scala/gitbucket/core/controller/DashboardController.scala
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/twirl/gitbucket/core/dashboard/issues.scala.html
  src/main/twirl/gitbucket/core/dashboard/pulls.scala.html
  src/main/twirl/gitbucket/core/dashboard/repos.scala.html
  src/main/twirl/gitbucket/core/dashboard/sidebar.scala.html
  src/main/twirl/gitbucket/core/dashboard/tab.scala.html
  src/main/twirl/gitbucket/core/index.scala.html
  src/main/twirl/gitbucket/core/search/repositories.scala.html
Labels: feature

#2005 Move Fork button to the header
  src/main/twirl/gitbucket/core/helper/forkrepository.scala.html
  src/main/twirl/gitbucket/core/menu.scala.html
  src/main/twirl/gitbucket/core/repo/forked.scala.html
Labels: improvement

#2065 Install plugins from the plugin registry
  build.sbt
  plugins.json
  src/main/resources/bundle-plugins.txt
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/plugin/PluginRegistry.scala
  src/main/scala/gitbucket/core/plugin/PluginRepository.scala
  src/main/scala/gitbucket/core/service/RepositoryService.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/scala/gitbucket/core/servlet/InitializeListener.scala
  src/main/twirl/gitbucket/core/account/menu.scala.html
  src/main/twirl/gitbucket/core/admin/plugins.scala.html
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/main/twirl/gitbucket/core/pulls/mergeguide.scala.html
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: feature

#2084 Add forwarding GitHub compatible LFS url
  src/main/scala/gitbucket/core/controller/PreProcessController.scala
Labels: bug
