Repository gitbucket/gitbucket, pull requests merged in 2018-03, with the labels that each got.

#1900 Git authentication by personal access tokens
  src/main/scala/gitbucket/core/servlet/GitAuthenticationFilter.scala
Labels: feature

#1907 Display commit message of tags in the release page
  src/main/scala/gitbucket/core/controller/ReleasesController.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/main/twirl/gitbucket/core/releases/form.scala.html
  src/main/twirl/gitbucket/core/releases/list.scala.html
  src/main/twirl/gitbucket/core/releases/release.scala.html
Labels: improvement

#1908 Add labels to ApiIssue/ApiPullRequest
  src/main/scala/gitbucket/core/api/ApiIssue.scala
  src/main/scala/gitbucket/core/api/ApiPullRequest.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/test/scala/gitbucket/core/api/JsonFormatSpec.scala
Labels: improvement

#1914 Prevent parsing filename as Markdown in conflict message
  src/main/scala/gitbucket/core/service/MergeService.scala
Labels: bug

#1902 Show banner to create a personal access token for OIDC users
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/scala/gitbucket/core/service/AccessTokenService.scala
  src/main/scala/gitbucket/core/service/AccountFederationService.scala
  src/main/twirl/gitbucket/core/index.scala.html
Labels: improvement

#1917 Add plugin list API
  src/main/scala/gitbucket/core/api/ApiPlugin.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
Labels: feature

#1921 Support all of paths which end with slash
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/ControllerBase.scala
  src/main/scala/gitbucket/core/controller/WikiController.scala
Labels: improvement

#1927 Render by plugin even if file is binary
  src/main/twirl/gitbucket/core/repo/blob.scala.html
Labels: improvement

#1928 Fix that Tomcat deployed with GitBucket can not shutdown.
  src/main/scala/gitbucket/core/servlet/InitializeListener.scala
Labels: improvement
