Repository gitbucket/gitbucket, pull requests merged in 2019-02, with the labels that each got.

#2261 Add documentation for remote debug
  doc/debug.md
  doc/readme.md
  doc/remote_debug.png
Labels: document

#2263 Add avatar to username completion
  src/main/scala/gitbucket/core/controller/IndexController.scala
Labels: improvement

#2262 Fix release activity link generation
  src/main/scala/gitbucket/core/controller/ReleasesController.scala
  src/main/scala/gitbucket/core/service/ActivityService.scala
  src/main/scala/gitbucket/core/view/helpers.scala
Labels: bug

#2269 add Open Graph Protocol support.
  src/main/twirl/gitbucket/core/main.scala.html
  src/main/webapp/assets/common/images/gitbucket_ogp.png
Labels: feature

#2271 handle .gitattributes
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
Labels: improvement

#2265 Add create/update a file API
  src/main/scala/gitbucket/core/api/CreateAFile.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryContentsControllerBase.scala
  src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala
Labels: APIv3

#2266 Add release API feature.
  src/main/scala/gitbucket/core/api/ApiRelease.scala
  src/main/scala/gitbucket/core/api/CreateARelease.scala
  src/main/scala/gitbucket/core/api/JsonFormat.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/api/ApiReleaseControllerBase.scala
  src/main/scala/gitbucket/core/service/ReleaseService.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
  src/test/scala/gitbucket/core/api/JsonFormatSpec.scala
Labels: APIv3
