Repository gitbucket/gitbucket, pull requests merged in 2019-03, with the labels that each got.

#2274 Implement creation of group via api
  src/main/scala/gitbucket/core/api/CreateAGroup.scala
  src/main/scala/gitbucket/core/controller/api/ApiOrganizationControllerBase.scala
  src/main/scala/gitbucket/core/service/AccountService.scala
Labels: APIv3

#2277 add parameter style token authentication
  src/main/scala/gitbucket/core/servlet/ApiAuthenticationFilter.scala
Labels: APIv3, improvement

#2264 Verify gpg sign
  src/main/resources/update/gitbucket-core_4.31.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/model/GpgKey.scala
  src/main/scala/gitbucket/core/model/Profile.scala
  src/main/scala/gitbucket/core/service/GpgKeyService.scala
  src/main/scala/gitbucket/core/util/GpgUtil.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/main/twirl/gitbucket/core/account/gpg.scala.html
  src/main/twirl/gitbucket/core/account/menu.scala.html
  src/main/twirl/gitbucket/core/repo/commits.scala.html
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
Labels: feature

#2290 switch to xhub4j-core 1.1.0 for java 9/11 compatibility
  build.sbt
Labels: improvement
