Repository gitbucket/gitbucket, pull requests merged in 2019-12, with the labels that each got.

#2398 Add assignee and assignees properties to some issues api payload
  src/main/scala/gitbucket/core/api/ApiIssue.scala
  src/main/scala/gitbucket/core/controller/api/ApiIssueControllerBase.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
  src/test/scala/gitbucket/core/api/JsonFormatSpec.scala
  src/test/scala/gitbucket/core/service/WebHookJsonFormatSpec.scala
Labels: APIv3

#2394 Change branch name text into link in PR page
  src/main/scala/gitbucket/core/view/helpers.scala
  src/main/twirl/gitbucket/core/pulls/menu.scala.html
Labels: improvement

#2405 Make pull request collapsable per file
  src/main/twirl/gitbucket/core/helper/diff.scala.html
  src/main/webapp/assets/common/css/gitbucket.css
Labels: feature

#2408 Configure CLI options via environmental variables
  src/main/java/JettyLauncher.java
  src/main/scala/gitbucket/core/plugin/PluginRegistry.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/scala/gitbucket/core/util/ConfigUtil.scala
  src/main/scala/gitbucket/core/util/DatabaseConfig.scala
  src/main/scala/gitbucket/core/util/FileUtil.scala
  src/main/scala/gitbucket/core/util/Validations.scala
Labels: improvement

#2388 Implement draft pull request related APIs
  src/main/scala/gitbucket/core/api/ApiPullRequest.scala
  src/main/scala/gitbucket/core/api/CreateAPullRequest.scala
  src/main/scala/gitbucket/core/controller/api/ApiPullRequestControllerBase.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
Labels: APIv3
