Repository gitbucket/gitbucket, pull requests merged in 2019-01, with the labels that each got.

#2233 add missing Webhook call
  src/main/scala/gitbucket/core/service/MergeService.scala
Labels: bug

#2234 supress webhook content-type logging
  src/main/scala/gitbucket/core/service/WebHookService.scala
Labels: improvement

#2239 Embedding filename to file icon tag
  src/main/twirl/gitbucket/core/releases/list.scala.html
  src/main/twirl/gitbucket/core/releases/release.scala.html
  src/main/twirl/gitbucket/core/repo/files.scala.html
Labels: improvement

#2242 Update developer’s documents
  doc/build.md
  doc/directory.md
  doc/licenses.md
  doc/readme.md
  doc/validation.md
Labels: document

#2246 Close classLoader when Plugin doesn't add
  src/main/scala/gitbucket/core/plugin/PluginRegistry.scala
Labels: bug

#2247 Correctly display "url" and "html_url" of API models
  src/main/scala/gitbucket/core/api/ApiCommit.scala
  src/main/scala/gitbucket/core/api/ApiCommits.scala
  src/main/scala/gitbucket/core/api/ApiRepository.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
Labels: improvement

#2252 Stop using JGit's RepositoryCache
  src/main/scala/gitbucket/core/servlet/GitAuthenticationFilter.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
  src/main/scala/gitbucket/core/util/Keys.scala
Labels: improvement
