Repository gitbucket/gitbucket, pull requests merged in 2019-06, with the labels that each got.

#2286 Improve API compatibility for SourceTree and Drone.io
  src/main/resources/update/gitbucket-core_4.32.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
  src/main/scala/gitbucket/core/api/ApiEmail.scala
  src/main/scala/gitbucket/core/api/ApiPermission.scala
  src/main/scala/gitbucket/core/api/ApiRepository.scala
  src/main/scala/gitbucket/core/api/ApiRepositoryWebhook.scala
  src/main/scala/gitbucket/core/api/ApiWebhook.scala
  src/main/scala/gitbucket/core/api/CreateAWebhook.scala
  src/main/scala/gitbucket/core/api/JsonFormat.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/api/ApiPullRequestControllerBase.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryControllerBase.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryWebhookcontrollerBase.scala
  src/main/scala/gitbucket/core/controller/api/ApiUserControllerBase.scala
  src/main/scala/gitbucket/core/model/Repository.scala
  src/main/scala/gitbucket/core/model/RepositoryWebHook.scala
  src/main/scala/gitbucket/core/service/RepositoryService.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
  src/test/scala/gitbucket/core/api/JsonFormatSpec.scala
  src/test/scala/gitbucket/core/service/WebHookServiceSpec.scala
Labels: APIv3

#2325 Make the compare view work properly even if commit id is specified
  src/main/twirl/gitbucket/core/pulls/compare.scala.html
Labels: improvement

#2330 Wrong file size issue when cloning and pulling contents via git-lfs.
  src/main/scala/gitbucket/core/servlet/GitLfsTransferServlet.scala
Labels: bug

#2333 docs: update issue & pull request template task lists
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: document

#2327 Milestone title should be unique #2256
  src/main/scala/gitbucket/core/controller/MilestonesController.scala
Labels: improvement

#2331 fix: issue save button disabled if after edited issue title once
  src/main/twirl/gitbucket/core/issues/issue.scala.html
Labels: bug
