Repository gitbucket/gitbucket, pull requests merged in 2020-07, with the labels that each got.

#2472 fix TLS/SSL LDAP under IBM JVM
  src/main/scala/gitbucket/core/util/LDAPUtil.scala
Labels: improvement

#2469 Repository operation restrictions
  .scalafmt.conf
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/main/twirl/gitbucket/core/main.scala.html
  src/main/twirl/gitbucket/core/menu.scala.html
  src/main/twirl/gitbucket/core/settings/danger.scala.html
  src/main/twirl/gitbucket/core/settings/options.scala.html
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: feature

#2473 theme: Add title to sidebar toggle button
  src/main/twirl/gitbucket/core/main.scala.html
Labels: improvement

#2470 Add get-commits-list-api
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryCommitControllerBase.scala
Labels: APIv3

#2474 executable: Allow saving sessions to disk
  src/main/java/JettyLauncher.java
Labels: improvement

#2468 Migrate activity log to JSON-based file from database
  build.sbt
  src/main/resources/update/gitbucket-core_4.34.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/DashboardController.scala
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/scala/gitbucket/core/controller/ReleasesController.scala
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/controller/WikiController.scala
  src/main/scala/gitbucket/core/model/Activity.scala
  src/main/scala/gitbucket/core/model/Profile.scala
  src/main/scala/gitbucket/core/service/ActivityService.scala
  src/main/scala/gitbucket/core/service/RepositoryService.scala
  src/main/scala/gitbucket/core/service/RequestCache.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
  src/main/scala/gitbucket/core/servlet/InitializeListener.scala
  src/main/scala/gitbucket/core/util/Directory.scala
  src/main/scala/gitbucket/core/view/AvatarImageProvider.scala
  src/main/scala/gitbucket/core/view/LinkConverter.scala
  src/main/scala/gitbucket/core/view/helpers.scala
  src/main/twirl/gitbucket/core/helper/activities.scala.html
  src/test/scala/gitbucket/core/service/MergeServiceSpec.scala
  src/test/scala/gitbucket/core/service/PullRequestServiceSpec.scala
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/service/WebHookServiceSpec.scala
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: improvement

#2488 Deny empty password
  src/main/scala/gitbucket/core/service/AccountService.scala
Labels: LDAP/SSO, bug

#2492 Fix system settings tab behavior
  src/main/twirl/gitbucket/core/admin/settings.scala.html
Labels: bug

#2491 Add function to close multiple issues with one keyword on commits
  src/main/scala/gitbucket/core/util/StringUtil.scala
  src/test/scala/gitbucket/core/util/StringUtilSpec.scala
Labels: feature

#2496 Fixed some grammar and spelling issues, modified sign in form
  src/main/twirl/gitbucket/core/account/hooks.scala.html
  src/main/twirl/gitbucket/core/account/newrepo.scala.html
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/main/twirl/gitbucket/core/dashboard/sidebar.scala.html
  src/main/twirl/gitbucket/core/main.scala.html
  src/main/twirl/gitbucket/core/settings/branches.scala.html
  src/main/twirl/gitbucket/core/settings/danger.scala.html
  src/main/twirl/gitbucket/core/settings/hooks.scala.html
  src/main/twirl/gitbucket/core/settings/options.scala.html
  src/main/twirl/gitbucket/core/signinform.scala.html
  src/main/twirl/gitbucket/core/wiki/edit.scala.html
Labels: improvement

#2482 Add Merge PullRequest API
  src/main/scala/gitbucket/core/api/MergeAPullRequest.scala
  src/main/scala/gitbucket/core/controller/api/ApiPullRequestControllerBase.scala
Labels: APIv3
