Repository gitbucket/gitbucket, pull requests merged in 2020-01, with the labels that each got.

#2416 Make Authorization header auth-scheme case-insencitive
  src/main/scala/ScalatraBootstrap.scala
  src/main/scala/gitbucket/core/servlet/ApiAuthenticationFilter.scala
  src/main/scala/gitbucket/core/util/Directory.scala
Labels: APIv3

#2417 Fix diff in compare view
  src/main/twirl/gitbucket/core/helper/diff.scala.html
Labels: bug

#2413 Restructure settings UI
  src/main/java/JettyLauncher.java
  src/main/scala/gitbucket/core/controller/FileUploadController.scala
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/scala/gitbucket/core/util/FileUtil.scala
  src/main/twirl/gitbucket/core/admin/settings.scala.html
  src/main/twirl/gitbucket/core/admin/settings_integrations.scala.html
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/main/twirl/gitbucket/core/helper/attached.scala.html
  src/main/twirl/gitbucket/core/releases/form.scala.html
  src/main/twirl/gitbucket/core/repo/upload.scala.html
  src/main/twirl/gitbucket/core/wiki/edit.scala.html
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: improvement

#2420 Correct activity message of reopening pull request
  README.md
  src/main/scala/gitbucket/core/service/ActivityService.scala
  src/main/scala/gitbucket/core/service/HandleCommentService.scala
Labels: bug

#2421 Limit the visible repositories in the sidebar.
  src/main/scala/gitbucket/core/controller/DashboardController.scala
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/service/RepositoryService.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: improvement
