Repository gitbucket/gitbucket, pull requests merged in 2020-09, with the labels that each got.

#2532 Show issue/PR title as a tooltip
  src/main/scala/gitbucket/core/view/LinkConverter.scala
  src/main/scala/gitbucket/core/view/helpers.scala
Labels: improvement

#2537 adding support for wiki page deletion recording
  src/main/scala/gitbucket/core/controller/WikiController.scala
  src/main/scala/gitbucket/core/model/activity/WikiActivityInfo.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
Labels: improvement

#2542 Add "has_issue" boolean to GET /repos/:owner/:repo API
  src/main/scala/gitbucket/core/api/ApiRepository.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
Labels: APIv3

#2536 Add get-an-issue-comment API endpoint
  src/main/scala/gitbucket/core/controller/api/ApiIssueCommentControllerBase.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
Labels: APIv3

#2534 Limit the number of characters for user completion and issue completioin
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/util/StringUtil.scala
  src/main/scala/gitbucket/core/view/helpers.scala
Labels: improvement

#2535 Add get-a-repository-README endpoint
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryContentsControllerBase.scala
  src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala
Labels: APIv3

#2538 Add update-an-issue-comment API
  src/main/scala/gitbucket/core/controller/api/ApiIssueCommentControllerBase.scala
  src/main/scala/gitbucket/core/plugin/IssueHook.scala
  src/main/scala/gitbucket/core/service/HandleCommentService.scala
Labels: APIv3

#2547 Add list-branches-for-head-commit API
  src/main/scala/gitbucket/core/api/ApiBranch.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryCommitControllerBase.scala
Labels: APIv3

#2540 adding support for GitHub v3 delete comment
  src/main/scala/gitbucket/core/controller/api/ApiIssueCommentControllerBase.scala
  src/main/scala/gitbucket/core/plugin/IssueHook.scala
  src/main/scala/gitbucket/core/service/HandleCommentService.scala
Labels: APIv3

#2550 Fix list commit api sha param
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryCommitControllerBase.scala
Labels: APIv3, bug

#2552 Improve accessibility
  .gitignore
  src/main/scala/gitbucket/core/view/AvatarImageProvider.scala
  src/main/twirl/gitbucket/core/account/edit.scala.html
  src/main/twirl/gitbucket/core/account/groupform.scala.html
  src/main/twirl/gitbucket/core/account/hooks.scala.html
  src/main/twirl/gitbucket/core/account/newrepo.scala.html
  src/main/twirl/gitbucket/core/admin/data.scala.html
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/main/twirl/gitbucket/core/admin/user.scala.html
  src/main/twirl/gitbucket/core/dashboard/issueslist.scala.html
  src/main/twirl/gitbucket/core/dashboard/repos.scala.html
  src/main/twirl/gitbucket/core/dashboard/sidebar.scala.html
  src/main/twirl/gitbucket/core/helper/account.scala.html
  src/main/twirl/gitbucket/core/helper/commitcomment.scala.html
  src/main/twirl/gitbucket/core/helper/datepicker.scala.html
  src/main/twirl/gitbucket/core/helper/dropdown.scala.html
  src/main/twirl/gitbucket/core/helper/preview.scala.html
  src/main/twirl/gitbucket/core/issues/commentform.scala.html
  src/main/twirl/gitbucket/core/issues/list.scala.html
  src/main/twirl/gitbucket/core/issues/listparts.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/edit.scala.html
  src/main/twirl/gitbucket/core/main.scala.html
  src/main/twirl/gitbucket/core/pulls/mergeguide.scala.html
  src/main/twirl/gitbucket/core/releases/form.scala.html
  src/main/twirl/gitbucket/core/repo/blob.scala.html
  src/main/twirl/gitbucket/core/repo/editor.scala.html
  src/main/twirl/gitbucket/core/repo/files.scala.html
  src/main/twirl/gitbucket/core/repo/find.scala.html
  src/main/twirl/gitbucket/core/settings/branches.scala.html
  src/main/twirl/gitbucket/core/settings/danger.scala.html
  src/main/twirl/gitbucket/core/settings/edithookform.scala.html
  src/main/twirl/gitbucket/core/settings/hooks.scala.html
  src/main/twirl/gitbucket/core/wiki/edit.scala.html
  src/main/twirl/gitbucket/core/wiki/history.scala.html
  src/main/twirl/gitbucket/core/wiki/page.scala.html
  src/main/webapp/assets/common/js/gitbucket.js
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: improvement

#2544 Add list repository tags API
  src/main/scala/gitbucket/core/api/ApiTag.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryControllerBase.scala
Labels: APIv3

#1965 force eol to lf by editorconfig / allow trailing space to *.md
  .editorconfig
Labels: improvement

#2551 Add repository webhook APIs
  src/main/resources/update/gitbucket-core_4.35.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
  src/main/scala/gitbucket/core/api/ApiWebhook.scala
  src/main/scala/gitbucket/core/api/CreateARepositoryWebhook.scala
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryWebhookControllerBase.scala
  src/main/scala/gitbucket/core/model/RepositoryWebHook.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/test/scala/gitbucket/core/service/WebHookServiceSpec.scala
Labels: APIv3

#2546 Add list-milestones and get-a-milestone API
  src/main/scala/gitbucket/core/api/ApiMilestone.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/api/ApiIssueMilestoneControllerBase.scala
Labels: APIv3

#2558 Add api endpoints for repository collaborator
  src/main/scala/gitbucket/core/api/ApiRepositoryCollaborator.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryCollaboratorControllerBase.scala
Labels: APIv3
