Repository gitbucket/gitbucket, pull requests merged in 2020-11, with the labels that each got.

#2581 Fix file name of the commit comment
  src/main/twirl/gitbucket/core/repo/commentform.scala.html
Labels: bug

#2518 Upload images from clipboard
  src/main/twirl/gitbucket/core/helper/attached.scala.html
Labels: feature

#2571 Add function to create new branch with commit on UI and start PR
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/twirl/gitbucket/core/repo/delete.scala.html
  src/main/twirl/gitbucket/core/repo/editor.scala.html
  src/main/twirl/gitbucket/core/repo/upload.scala.html
Labels: feature

#2548 Use attr() instead of data() to prevent parsing of json
  src/main/webapp/assets/common/js/gitbucket.js
Labels: bug

#2590 Implement API for creating, updating and deleting refs.
  src/main/scala/gitbucket/core/api/CreateARef.scala
  src/main/scala/gitbucket/core/api/UpdateARef.scala
  src/main/scala/gitbucket/core/controller/api/ApiGitReferenceControllerBase.scala
  src/main/scala/gitbucket/core/controller/api/ApiIssueCommentControllerBase.scala
Labels: APIv3
