Repository gitbucket/gitbucket, pull requests merged in 2020-08, with the labels that each got.

#2497 Move the settings link down
  src/main/twirl/gitbucket/core/menu.scala.html
Labels: improvement

#2500 Show the number of milestones on the sidebar menu
  src/main/scala/gitbucket/core/service/RepositoryService.scala
  src/main/twirl/gitbucket/core/menu.scala.html
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
Labels: improvement

#2501 Add theme choices for editor
  src/main/twirl/gitbucket/core/repo/editor.scala.html
Labels: feature

#2511 Max files for getting commit info becomes configurable
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryContentsControllerBase.scala
  src/main/scala/gitbucket/core/service/RepositoryService.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: improvement

#2510 Add activity record for issue closing by comment
  src/main/scala/gitbucket/core/service/MergeService.scala
  src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
Labels: improvement

#2514 Keep the default branch in the forked repositories
  src/main/scala/gitbucket/core/service/RepositoryCreationService.scala
  src/main/scala/gitbucket/core/service/RepositoryService.scala
Labels: improvement

#2516 Show userName as link only when a user is not removed
  src/main/twirl/gitbucket/core/admin/userlist.scala.html
Labels: improvement

#2513 Add issue completion
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/plugin/PluginRegistry.scala
  src/main/scala/gitbucket/core/plugin/SuggestionProvider.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/twirl/gitbucket/core/helper/attached.scala.html
Labels: feature

#2525 Support update latest activity date for commits file via WebUI
  src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala
Labels: improvement

#2526 refactored ActivityService logging strategy
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/scala/gitbucket/core/controller/ReleasesController.scala
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/controller/WikiController.scala
  src/main/scala/gitbucket/core/model/activity/BaseActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/BranchActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/CommentActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/ForkActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/IssueActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/MergeActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/ReleaseActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/RepositoryActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/TagActivityInfo.scala
  src/main/scala/gitbucket/core/model/activity/WikiActivityInfo.scala
  src/main/scala/gitbucket/core/service/ActivityService.scala
  src/main/scala/gitbucket/core/service/CommitsService.scala
  src/main/scala/gitbucket/core/service/HandleCommentService.scala
  src/main/scala/gitbucket/core/service/IssueCreationService.scala
  src/main/scala/gitbucket/core/service/MergeService.scala
  src/main/scala/gitbucket/core/service/PullRequestService.scala
  src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala
  src/main/scala/gitbucket/core/service/RepositoryCreationService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
Labels: improvement

#2529 Add list-public-repositories API
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryControllerBase.scala
  src/main/scala/gitbucket/core/service/RepositoryService.scala
Labels: APIv3
