Repository gitbucket/gitbucket, pull requests merged in 2020-06, with the labels that each got.

#2458 Use-defined CSS
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/twirl/gitbucket/core/admin/settings_system.scala.html
  src/main/twirl/gitbucket/core/main.scala.html
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/view/AvatarImageProviderSpec.scala
Labels: feature

#2459 Fix get a reference API path
  src/main/scala/gitbucket/core/controller/api/ApiGitReferenceControllerBase.scala
Labels: APIv3, bug

#2449 Apply the trustStore setting when ssl is true - Fixes #1782
  src/main/scala/gitbucket/core/util/LDAPUtil.scala
Labels: LDAP/SSO

#2466 Improve file list performance
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/main/twirl/gitbucket/core/helper/datetimeago.scala.html
Labels: improvement
