Repository gitbucket/gitbucket, pull requests merged in 2020-12, with the labels that each got.

#2600 Fix branch protection setting API
  src/main/scala/gitbucket/core/api/ApiBranchProtection.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
  src/test/scala/gitbucket/core/api/JsonFormatSpec.scala
Labels: APIv3, bug

#2586 Add milestone page
  src/main/scala/gitbucket/core/api/ApiMilestone.scala
  src/main/scala/gitbucket/core/controller/DashboardController.scala
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/controller/MilestonesController.scala
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
  src/main/twirl/gitbucket/core/issues/list.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/list.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/listparts.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/milestone.scala.html
Labels: feature

#2588 Improve issue comment management
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/service/HandleCommentService.scala
  src/main/scala/gitbucket/core/service/IssueCreationService.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/twirl/gitbucket/core/issues/commentlist.scala.html
  src/main/twirl/gitbucket/core/issues/issue.scala.html
  src/main/webapp/assets/common/css/gitbucket.css
Labels: improvement

#2601 Show the commit status in various places
  src/main/scala/gitbucket/core/controller/DashboardController.scala
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/controller/MilestonesController.scala
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryStatusControllerBase.scala
  src/main/scala/gitbucket/core/service/CommitStatusService.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/service/ProtectedBranchService.scala
  src/main/scala/gitbucket/core/service/PullRequestService.scala
  src/main/twirl/gitbucket/core/dashboard/issues.scala.html
  src/main/twirl/gitbucket/core/dashboard/issueslist.scala.html
  src/main/twirl/gitbucket/core/dashboard/pulls.scala.html
  src/main/twirl/gitbucket/core/helper/commitstatus.scala.html
  src/main/twirl/gitbucket/core/issues/commitstatus.scala.html
  src/main/twirl/gitbucket/core/issues/list.scala.html
  src/main/twirl/gitbucket/core/issues/listparts.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/listparts.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/milestone.scala.html
  src/main/twirl/gitbucket/core/main.scala.html
  src/main/twirl/gitbucket/core/repo/branches.scala.html
  src/main/twirl/gitbucket/core/repo/commit.scala.html
  src/main/twirl/gitbucket/core/repo/commits.scala.html
  src/main/twirl/gitbucket/core/repo/files.scala.html
  src/main/webapp/assets/vendors/tipped/tipped.css
  src/main/webapp/assets/vendors/tipped/tipped.min.js
  src/test/scala/gitbucket/core/service/IssuesServiceSpec.scala
Labels: improvement

#2520 Call ReceiveHook when pull request is merged
  build.sbt
  src/main/scala/gitbucket/core/plugin/ReceiveHook.scala
  src/main/scala/gitbucket/core/service/MergeService.scala
  src/main/scala/gitbucket/core/service/ProtectedBranchService.scala
  src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
  src/test/scala/gitbucket/core/service/MergeServiceSpec.scala
  src/test/scala/gitbucket/core/service/ProtectedBranchServiceSpec.scala
Labels: improvement

#2603 Fix issue title on milestone page
  src/main/twirl/gitbucket/core/issues/milestones/listparts.scala.html
Labels: bug

#2606 Show commit status at commits tab of pull request
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/twirl/gitbucket/core/pulls/commits.scala.html
Labels: improvement

#2610 Fix WEB_HOOK table migration issue in 4.35.0
  src/main/resources/update/gitbucket-core_4.35.xml
  src/main/scala/gitbucket/core/service/WebHookService.scala
Labels: bug

#2611 Call webhook when pull request is merged
  src/main/scala/gitbucket/core/service/MergeService.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/test/scala/gitbucket/core/service/MergeServiceSpec.scala
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/util/GitSpecUtil.scala
Labels: improvement
