Repository gitbucket/gitbucket, pull requests merged in 2021-11, with the labels that each got.

#2908 resolve #2907 API - not milestone data in issue list
  src/main/scala/gitbucket/core/api/ApiIssue.scala
  src/main/scala/gitbucket/core/controller/api/ApiIssueControllerBase.scala
  src/main/scala/gitbucket/core/controller/api/ApiIssueMilestoneControllerBase.scala
  src/main/scala/gitbucket/core/service/MilestonesService.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
  src/test/scala/gitbucket/core/service/WebHookJsonFormatSpec.scala
Labels: improvement, APIv3

#2913 Fix duplicated diff issue in patch
  src/main/scala/gitbucket/core/util/JGitUtil.scala
Labels: bug

#2915 Relax max length limitation for WebHook URLs
  src/main/resources/update/gitbucket-core_4.37.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
Labels: improvement

#2922 Remove unnecessary loading of google-code-prettify
  src/main/twirl/gitbucket/core/helper/preview.scala.html
Labels: improvement

#2921 Fix line highlighting in dark syntax highlighter themes
  src/main/twirl/gitbucket/core/repo/blob.scala.html
Labels: bug

#2929 Bump apache-sshd to 2.7.0
  build.sbt
  src/main/scala/gitbucket/core/ssh/GitCommand.scala
  src/main/scala/gitbucket/core/ssh/NoShell.scala
  src/main/scala/gitbucket/core/ssh/PublicKeyAuthenticator.scala
  src/test/scala/gitbucket/core/ssh/GitCommandSpec.scala
Labels: improvement

#2930 Fix SSH server handling
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/ssh/SshServerListener.scala
Labels: bug
