Repository gitbucket/gitbucket, pull requests merged in 2021-04, with the labels that each got.

#2608 Add function to refer issue/PR of other repositories within issue/PR conversations
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/util/StringUtil.scala
  src/main/scala/gitbucket/core/view/LinkConverter.scala
  src/main/scala/gitbucket/core/view/helpers.scala
  src/main/twirl/gitbucket/core/issues/commentlist.scala.html
  src/test/scala/gitbucket/core/util/StringUtilSpec.scala
Labels: feature

#2725 Fix repository creation permission check
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryControllerBase.scala
  src/main/scala/gitbucket/core/service/RepositoryCreationService.scala
  src/main/scala/gitbucket/core/util/Authenticator.scala
Labels: bug

#2731 Abolish the pull request title length limitation
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
Labels: improvement

#2732 (bugfix) password msg when editing an LDAP profile
  src/main/twirl/gitbucket/core/account/edit.scala.html
Labels: bug

#2744 Minor fix for WebHook testing UI
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
  src/main/twirl/gitbucket/core/settings/edithookform.scala.html
Labels: bug

#2745 Use account name as pusher for commits by WebUI
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryContentsControllerBase.scala
  src/main/scala/gitbucket/core/service/MergeService.scala
  src/main/scala/gitbucket/core/service/PullRequestService.scala
  src/main/scala/gitbucket/core/service/RepositoryCommitFileService.scala
Labels: improvement
