Repository gitbucket/gitbucket, pull requests merged in 2021-02, with the labels that each got.

#2660 As is, the unsuspend API cannot unsuspend since it's not searching su…
  src/main/scala/gitbucket/core/controller/api/ApiUserControllerBase.scala
Labels: APIv3, bug

#2684 Fix issue / pull request view templates
  src/main/twirl/gitbucket/core/issues/commentform.scala.html
  src/main/twirl/gitbucket/core/issues/issueinfo.scala.html
  src/main/twirl/gitbucket/core/pulls/conversation.scala.html
Labels: bug

#2664 Prevent execution of empty SQL strings during database import
  src/main/scala/gitbucket/core/util/JDBCUtil.scala
Labels: improvement

#2685 Links to files and lines in the diff view
  src/main/scala/gitbucket/core/view/helpers.scala
  src/main/twirl/gitbucket/core/helper/diff.scala.html
  src/main/twirl/gitbucket/core/repo/blob.scala.html
  src/main/webapp/assets/common/css/gitbucket.css
  src/main/webapp/assets/common/js/gitbucket.js
Labels: improvement

#2694 Make developer documentation a separate section in main readme
  README.md
Labels: document
