Repository gitbucket/gitbucket, pull requests merged in 2022-05, with the labels that each got.

#3053 Fix wrong overwriting of updatedDate of Issues and Pull requests
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/service/HandleCommentService.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
Labels: bug

#3056 Refactor old migrations
  src/main/resources/update/gitbucket-core_4.0.sql
  src/main/resources/update/gitbucket-core_4.0.xml
  src/main/resources/update/gitbucket-core_4.14.sql
  src/main/resources/update/gitbucket-core_4.14.xml
  src/main/resources/update/gitbucket-core_4.7.sql
  src/main/resources/update/gitbucket-core_4.7.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
Labels: improvement

#3055 Support multiple assignees for Issues and Pull requests
  src/main/resources/update/gitbucket-core_4.38.xml
  src/main/scala/gitbucket/core/api/ApiIssue.scala
  src/main/scala/gitbucket/core/api/ApiPullRequest.scala
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/controller/LabelsController.scala
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/controller/api/ApiIssueControllerBase.scala
  src/main/scala/gitbucket/core/controller/api/ApiPullRequestControllerBase.scala
  src/main/scala/gitbucket/core/model/Issue.scala
  src/main/scala/gitbucket/core/model/IssueAssignee.scala
  src/main/scala/gitbucket/core/model/Profile.scala
  src/main/scala/gitbucket/core/service/IssueCreationService.scala
  src/main/scala/gitbucket/core/service/IssuesService.scala
  src/main/scala/gitbucket/core/service/WebHookService.scala
  src/main/twirl/gitbucket/core/dashboard/issueslist.scala.html
  src/main/twirl/gitbucket/core/issues/commentlist.scala.html
  src/main/twirl/gitbucket/core/issues/create.scala.html
  src/main/twirl/gitbucket/core/issues/issue.scala.html
  src/main/twirl/gitbucket/core/issues/issueinfo.scala.html
  src/main/twirl/gitbucket/core/issues/listparts.scala.html
  src/main/twirl/gitbucket/core/issues/milestones/listparts.scala.html
  src/main/twirl/gitbucket/core/pulls/compare.scala.html
  src/main/twirl/gitbucket/core/pulls/conversation.scala.html
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
  src/test/scala/gitbucket/core/service/ServiceSpecBase.scala
  src/test/scala/gitbucket/core/service/WebHookJsonFormatSpec.scala
  src/test/scala/gitbucket/core/view/PaginationSpec.scala
Labels: feature

#3061 Implement missing parameters on commits api
  src/main/scala/gitbucket/core/api/ApiCommits.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryCommitControllerBase.scala
  src/test/scala/gitbucket/core/api/ApiSpecModels.scala
Labels: APIv3
