Repository gitbucket/gitbucket, pull requests merged in 2024-12, with the labels that each got.

#3650 Update build.md about testing on Jetty from sbt
  doc/build.md
Labels: document

#3647 Calculate diffs between commits based on common ancestor; works …
  src/main/scala/gitbucket/core/controller/ReleasesController.scala
  src/main/scala/gitbucket/core/util/JGitUtil.scala
  src/test/scala/gitbucket/core/util/JGitUtilSpec.scala
Labels: improvement

#3661 Apply user-defined CSS after plugins' JavaScript runs
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/twirl/gitbucket/core/main.scala.html
Labels: improvement

#3662 Restore the original response of list-repository-tags API
  src/main/scala/gitbucket/core/api/ApiTag.scala
  src/main/scala/gitbucket/core/controller/api/ApiRepositoryControllerBase.scala
  src/test/scala/gitbucket/core/api/ApiIntegrationTest.scala
Labels: bug, APIv3

#3656 Fix ref and ssh_url in WebHook payloads
  src/main/scala/gitbucket/core/api/ApiRepository.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/service/SystemSettingsService.scala
  src/main/scala/gitbucket/core/servlet/GitRepositoryServlet.scala
  src/main/scala/gitbucket/core/ssh/GitCommand.scala
  src/test/scala/gitbucket/core/service/SystemSettingsServiceSpec.scala
Labels: bug

#3667 Show branch errors when creating pull request
  src/main/twirl/gitbucket/core/pulls/compare.scala.html
Labels: improvement

#3670 Stabilize AccountServiceSpec
  src/test/scala/gitbucket/core/service/AccountServiceSpec.scala
Labels: improvement

#3669 Fix wrong redirection when non-existent branch name is given as default branch
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
Labels: bug

#3672 Return 400 error for invalid query string
  src/main/scala/gitbucket/core/controller/ControllerBase.scala
Labels: improvement

#3673 Fix warnings in ControllerBase
  src/main/scala/gitbucket/core/controller/ControllerBase.scala
Labels: improvement

#3674 Fix warnings in controllers
  src/main/scala/gitbucket/core/controller/AccountController.scala
  src/main/scala/gitbucket/core/controller/ApiController.scala
  src/main/scala/gitbucket/core/controller/DashboardController.scala
  src/main/scala/gitbucket/core/controller/FileUploadController.scala
  src/main/scala/gitbucket/core/controller/IndexController.scala
  src/main/scala/gitbucket/core/controller/IssuesController.scala
  src/main/scala/gitbucket/core/controller/LabelsController.scala
  src/main/scala/gitbucket/core/controller/MilestonesController.scala
  src/main/scala/gitbucket/core/controller/PrioritiesController.scala
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
  src/main/scala/gitbucket/core/controller/ReleasesController.scala
  src/main/scala/gitbucket/core/controller/RepositorySettingsController.scala
  src/main/scala/gitbucket/core/controller/RepositoryViewerController.scala
  src/main/scala/gitbucket/core/controller/SystemSettingsController.scala
  src/main/scala/gitbucket/core/controller/ValidationSupport.scala
  src/main/scala/gitbucket/core/controller/WikiController.scala
Labels: improvement

#3676 Increase max branch name length 100 -> 255
  src/main/resources/update/gitbucket-core_4.42.xml
  src/main/scala/gitbucket/core/GitBucketCoreModule.scala
  src/main/scala/gitbucket/core/controller/PullRequestsController.scala
Labels: improvement
